"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import { exportBusinessPdf, exportBusinessWord, type BusinessExport } from "../lib/business-exports";
import { businessIsoDate } from "../lib/date-utils";
import { readStoredArray, readStoredObject, STORAGE_KEYS, writeStoredJson } from "../lib/storage";
import { VOLIA_LOGO_DATA_URL } from "../lib/volia-logo";
import { recordActivity } from "../lib/activity-log";

type DocType = "implants" | "delivery" | "technical" | "payment";
type DocData = { type: DocType; number: string; date: string; recipient: string; role: string; institution: string; patient: string; patientId: string; hcl: string; surgeryDate: string; contract: string; subject: string; detail: string; amount: string; signer: string; signerRole: string };
type StoredDocument = { id: string; savedAt: string; data: DocData };
const KEY = "volia-document-draft-v1";
const TYPES: Record<DocType, { label: string; subject: string; intro: string }> = {
  implants: { label: "Carta de implantes utilizados", subject: "Detalle de implantes utilizados", intro: "Por medio de la presente se deja constancia de los dispositivos e insumos utilizados durante el procedimiento indicado." },
  delivery: { label: "Acta de entrega-recepción", subject: "Entrega de equipos e insumos", intro: "Las partes dejan constancia de la entrega y recepción conforme de los bienes detallados a continuación." },
  technical: { label: "Informe técnico", subject: "Informe técnico de revisión", intro: "Se presenta el resultado de la revisión técnica efectuada, incluyendo antecedentes, hallazgos y recomendaciones." },
  payment: { label: "Solicitud de pago", subject: "Solicitud de pago por bienes entregados", intro: "Se solicita gestionar el pago correspondiente a los bienes y servicios entregados conforme al proceso indicado." },
};
const today = businessIsoDate;
const INITIAL: DocData = { type: "implants", number: `VOL-DOC-${today().replaceAll('-','')}`, date: today(), recipient: "", role: "", institution: "", patient: "", patientId: "", hcl: "", surgeryDate: "", contract: "", subject: TYPES.implants.subject, detail: "", amount: "", signer: "", signerRole: "Representante autorizado de VOLIA S.A.S." };

export default function DocumentGenerator() {
  const [data, setData] = useState(INITIAL); const [ready, setReady] = useState(false); const [history, setHistory] = useState<StoredDocument[]>([]);
  useEffect(() => { const timer = window.setTimeout(() => { setData(readStoredObject(KEY, INITIAL)); setHistory(readStoredArray<StoredDocument>(STORAGE_KEYS.documentHistory)); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (ready) writeStoredJson(KEY, data); }, [data, ready]);
  const setType = (type: DocType) => setData((current) => ({ ...current, type, subject: TYPES[type].subject }));
  const field = (key: keyof DocData, value: string) => setData((current) => ({ ...current, [key]: value }));
  const exportPayload = (): BusinessExport => ({ title: TYPES[data.type].label, subtitle: data.subject, reference: `${data.number || "Sin número"} · ${data.date || "Sin fecha"}`, metadata: [["Destinatario", data.recipient], ["Cargo", data.role], ["Institución", data.institution], ["Paciente", data.patient], ["CI / HCL", `${data.patientId || "—"} / ${data.hcl || "—"}`], ["Fecha de cirugía", data.surgeryDate], ["Contrato / proceso", data.contract], ["Firmante", data.signer]], paragraphs: [TYPES[data.type].intro, data.detail || "Detalle pendiente de completar.", ...(data.amount ? [`Valor relacionado: USD ${Number(data.amount).toLocaleString("es-EC", { minimumFractionDigits: 2 })}`] : []), "Particular que comunico para los fines pertinentes."], disclaimer: "Documento institucional de VOLIA S.A.S. Revisión, aprobación y firma humana obligatorias antes de su emisión." });
  const archive = () => { const snapshot: StoredDocument = { id: `${Date.now()}`, savedAt: new Date().toISOString(), data: { ...data } }; const next = [snapshot, ...history.filter((entry) => entry.data.number !== data.number)].slice(0, 100); setHistory(next); writeStoredJson(STORAGE_KEYS.documentHistory, next); recordActivity("Documentos", "Documento archivado", `${data.number || "Sin número"} · ${TYPES[data.type].label}`); };
  const downloadPdf = () => { archive(); exportBusinessPdf(exportPayload(), data.number || TYPES[data.type].label); };
  const downloadWord = () => { archive(); exportBusinessWord(exportPayload(), data.number || TYPES[data.type].label); };
  const restore = (entry: StoredDocument) => { setData({ ...entry.data }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <section className="business-module document-module"><div className="module-hero"><div><p className="eyebrow">AUTOMATIZACIÓN ADMINISTRATIVA</p><h2>Generador de documentos</h2><p>Completa una sola ficha y produce cartas, actas e informes con presentación institucional uniforme.</p></div><div className="hero-actions"><button className="primary-button" onClick={downloadPdf}>Descargar PDF</button><button className="secondary-button" onClick={downloadWord}>Descargar Word</button><button className="secondary-button" onClick={() => window.print()}>Imprimir</button></div></div>
    {history.length > 0 && <details className="quote-memory"><summary><span>ARCHIVO DOCUMENTAL</span><strong>{history.length} documento(s) guardado(s)</strong></summary><div className="quote-memory-list">{history.slice(0,10).map((entry) => <article key={entry.id}><div><strong>{entry.data.number || "Sin número"}</strong><span>{TYPES[entry.data.type].label} · {entry.data.recipient || "Sin destinatario"}</span></div><button onClick={() => restore(entry)}>Abrir</button></article>)}</div></details>}
    <div className="document-builder"><section className="business-card document-form"><div className="section-heading"><div><p className="eyebrow">PLANTILLA</p><h3>Datos del documento</h3></div></div><label><span>Tipo de documento</span><select value={data.type} onChange={(e) => setType(e.target.value as DocType)}>{Object.entries(TYPES).map(([key,type]) => <option value={key} key={key}>{type.label}</option>)}</select></label><div className="business-form two">{([['number','Número'],['date','Fecha'],['recipient','Destinatario'],['role','Cargo'],['institution','Institución'],['contract','Contrato / proceso'],['patient','Paciente'],['patientId','Cédula'],['hcl','HCL'],['surgeryDate','Fecha de cirugía'],['amount','Valor relacionado (USD)'],['signer','Firmante'],['signerRole','Cargo del firmante'],['subject','Asunto']] as const).map(([key,label]) => <label key={key} className={key === 'subject' ? 'wide-field' : ''}><span>{label}</span><input type={key === 'date' || key === 'surgeryDate' ? 'date' : key === 'amount' ? 'number' : 'text'} min={key === 'amount' ? '0' : undefined} step={key === 'amount' ? '.01' : undefined} value={data[key]} onChange={(e) => field(key,e.target.value)} /></label>)}</div><label><span>Detalle, bienes, hallazgos o petición</span><textarea rows={8} placeholder="Escriba aquí el contenido específico. Puede usar varias líneas." value={data.detail} onChange={(e) => field('detail',e.target.value)} /></label><p className="local-note">Borrador autoguardado únicamente en este dispositivo.</p></section>
      <section className="generated-document" aria-label="Documento generado"><header><div className="doc-brand"><img src={VOLIA_LOGO_DATA_URL} alt="Volia S.A.S." width="105" height="50" /><div><strong>VOLIA S.A.S.</strong><small>Insumos y equipos médico-quirúrgicos</small></div></div><div className="doc-reference"><strong>{data.number || 'SIN NÚMERO'}</strong><span>Quito, {data.date || 'sin fecha'}</span></div></header><div className="doc-addressee"><strong>{data.recipient || 'DESTINATARIO'}</strong><span>{data.role || 'Cargo por definir'}</span><span>{data.institution || 'Institución por definir'}</span></div><p><strong>Asunto: {data.subject}</strong></p><p>De mi consideración:</p><p>{TYPES[data.type].intro}</p>{(data.patient || data.contract) && <div className="doc-data-grid"><div><span>Paciente</span><strong>{data.patient || '—'}</strong></div><div><span>CI / HCL</span><strong>{data.patientId || '—'} / {data.hcl || '—'}</strong></div><div><span>Fecha de cirugía</span><strong>{data.surgeryDate || '—'}</strong></div><div><span>Contrato / proceso</span><strong>{data.contract || '—'}</strong></div></div>}<div className="doc-body">{data.detail ? data.detail.split('\n').map((line,index) => <p key={index}>{line || <>&nbsp;</>}</p>) : <p className="placeholder-copy">Ingrese el detalle del documento en el formulario.</p>}</div>{data.amount && <p><strong>Valor relacionado: USD {Number(data.amount).toLocaleString('es-EC',{minimumFractionDigits:2,maximumFractionDigits:2})}</strong></p>}<p>Particular que comunico para los fines pertinentes.</p><div className="signature-space"><span>Atentamente,</span><div></div><strong>{data.signer}</strong><small>{data.signerRole}</small><small>VOLIA S.A.S.</small></div><footer><span>Documento institucional de VOLIA S.A.S.</span><strong>Revisión y firma humana obligatorias antes de su emisión</strong></footer></section>
    </div>
  </section>;
}
